### ISSUE TITLE
Technology stack contain proprietary software i.e Windows

### ISSUE THREAD

**Issue by boddulavineela** [SoftwareEngineeringToolDemos/ICSE-12-javamop#8]
Tool is Java application. Could have used Linux OS which is not proprietary.

**Comment by anshitasayal** [comment]
I tried to get the tool working on Ubuntu VM before the first VM submission deadline. On running the tool I got the LogicEngine null error. Due to lack of proper guidance about the releases of the tool, I submitted the Windows VM for the submission on which the tool runs absolutely fine. I got the following error on Ubuntu VM:

-Processing HasNext.mop
 HasNext.rvm is generated
 HasNextMonitorAspect.aj is generated
-Processing HasNext.rvm
Logic Engine Error: null

On getting in touch with the author I found out that the issue was with the most stable release of the tool. The author advised me to use the LATEST release of javamop tool by cloning the github repository code. This resolution was obtained after the first VM submission date. 

I have successfully got the tool working on Ubuntu 14.04. 

Closing #8. The updated ova file has been uploaded to the google drive.
